### Throughout this exercise, you may need to refer to online documentation.

Pandas: http://pandas.pydata.org/pandas-docs/stable/

Numpy & Scipy: https://docs.scipy.org/doc/

In [2]:
# First, import packages and load some data
import pandas      as pd
import numpy       as np
import scipy       as sp
import scipy.stats as stats

datafile = './pima-indians-diabetes.csv'

df = pd.read_csv(datafile, header=0, index_col=None)
df

,times_pregnant,plasma_glucose_concentration,diastolic_blood_pressure,triceps_thickness,2-hour_serum_insulin,BMI,diabetes_pedigreen,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
# Missing data is coded as 0 in all but the first and last columns (where 0 is meaningful)
# Change 0s in columns 1-7 to np.nan

# Hint: you can conditionally assign slices of a dataframe to a new value:
# eg. df[df[c]==x] = v  will change values in column c to v where they were originall x.
# And remember you can slice multiple columns with as df[[0,1]] for the first two columns
# You can also look at pandas' DataFrame.replace() function

In [ ]:
# The basics: counts, min, max, mean, median and mode
# Get the count (of all non-NaNs), min, max, mean, median and mode of each column.

# Hint 1: use numpy's min(), max(), nanmean() and nanmedian() functions.
# Hint 2: scipy.stats has a mode function ... but it returns a complex object.

# Which column has the most missing values?
print "Column,Count,Min,Max,Mean,Median,Mode"
for col in df.columns:
    # go...

In [ ]:
# Now let's try to better characterize the column distributions.
# First, we can "centre" each column (also called a z-transform) so that it has mean=0, variance=1
# To center a value, we simply subtract the mean of the distribution, and divide that value 
#   by the standard deviation of the distribution:
# for each value v in a distribution of values V:
#    v = (v-mean(V)) / std(V)

# Write a centre() function
# Hint: centre([0,1,2,3,5,10]) => [-1.059, -0.757, -0.454, -0.151, 0.454, 1.967]

# Remember to use np.nanmean() and np.nanstd() to deal with NaNs
def centre(v):
    """Returns a copy of array `v with centred values"""

In [ ]:
# Let's make a copy of df, to hold the centred values:
cdf = df.copy()

In [ ]:
# Now fill in cdf by applying your centre() function to each column in df

In [ ]:
# Finally! Let's look for outliers by getting the min and max in the new centred df:
# (You can re-use code from above!)

print "Column,Min,Max"
for col in cdf.columns:
    # go...

In [ ]:
# trick question:
# What is the mean of cdf['times_pregnant']?
# Why isn't it zero?